# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f40eca8fa5db52b330a9a69f25bfecea78e85721023f1217467fc6071560289188751de56ca8bbb18a2d9558ea54a83eb815450138ddd689258a843ba98c6eb4

test:
  secret_key_base: e144b19efdc1f733598b0d48c95accb0df12a4cfbb33423d8fdfb6b85f0296cfa44a6198cc225fdb2184701694f9858eceaf83abd84a51b6f33312ccb94fb094

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
